PmClup/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PmClup.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }
    }
}

PmClup/Controllers/FairsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PmClup.Controllers
{
    public class FairsController : Controller
    {
        // GET: Fairs
        public ActionResult Modef()
        {
            return View();
        }
        public ActionResult Imob()
        {
            return View();
        }
        public ActionResult ModefExpo()
        {
            return View();
        }
        public ActionResult Modef2015()
        {
            return View();
        }
    }
}

PmClup/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PmClup.Controllers
{
    public class HomeController : Controller
    {
        /// <summary>
        /// Home Index
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Kurumsal
        /// </summary>
        /// <returns></returns>
        public ActionResult Corporate()
        {
            return View();
        }
    }
}

PmClup/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PmClup.Controllers
{
    public class ProductsController : Controller
    {
        // GET: Products
        public ActionResult CornerSofa()
        {
            return View();
        }
        public ActionResult Puffs()
        {
            return View();
        }
        public ActionResult ArmchairFor()
        {
            return View();
        }
        public ActionResult SofaSuit()
        {
            return View();
        }


    }
}

PmClup/Views/Contact/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Sahram</h2>

PmClup/Views/Fairs/Imob.cshtml
@{
    ViewBag.Title = "Imob";
}

<h2>Imob</h2>

PmClup/Views/Fairs/Modef.cshtml
@{
    ViewBag.Title = "Modef";
}

<!-- SUB BANNER -->
<section class="sub-bnr" style="background:url(images/bg/sub-bnr-bg-3.jpg) no-repeat;" data-stellar-background-ratio="0.5">
    <div class="position-center-center">
        <div class="container">
            <h1>company presentation</h1>
            <!-- Breadcrumbs -->
            <ol class="breadcrumb">
                <li><a href="#">Home</a></li>
                <li class="active">company presentation</li>
            </ol>
        </div>
    </div>
</section>

<!-- Content -->
<div id="content">

    <!-- Company Presentation -->
    <section class="presentation padding-top-70 padding-bottom-70">
        <div class="container">

            <!-- Heading -->
            <div class="heading text-center">
                <span>january 2, 2015</span>
                <h4>Culture Code: Creating A Lovable Company</h4>
                <p>Donec venenatis, turpis vel hendrerit interdum, dui ligula ultricies purus, sed posuere libero dui id orci. Nam congue, pede vitae dapibus aliquet interdum dui ligula ultricies purus, sed posuere. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ea, nihil, dolores, culpa ullam vero ipsum placeat accusamus nemo ipsa cupiditate id molestiae consectetur quae pariatur repudiandae vel ex quaerat nam iusto aliquid laborum quia adipisci aut ut impedit obcaecati nisi deleniti tempore maxime. </p>
            </div>
            <div class="single-slide">
                <div class="item"> <img class="img-responsive" src="images/pre-img-1.jpg" alt=""> </div>
                <div class="item"> <img class="img-responsive" src="images/pre-img-4.jpg" alt=""> </div>
                <div class="item"> <img class="img-responsive" src="images/pre-img-3.jpg" alt=""> </div>
            </div>
        </div>
    </section>
</div>

PmClup/Views/Fairs/Modef2015.cshtml
@{
    ViewBag.Title = "Modef2015";
}

<h2>Modef2015</h2>

PmClup/Views/Fairs/ModefExpo.cshtml
@{
    ViewBag.Title = "ModefExpo";
}

<h2>ModefExpo</h2>

PmClup/Views/Products/ArmchairFor.cshtml
@{
    ViewBag.Title = "ArmchairFor";
}

<div class="col-md-12">
    <div class="col-md-3">
        <div class="job-sider-bar">
            <h5 class="side-tittle"> </h5>
            <!-- Recent Reviews -->

            <div class="items-side-bar">
                <ul>
                    <li>
                        <h6 class="head"><a data-toggle="collapse" href="#Stories" aria-expanded="false"><i class="fa fa-comments-o"></i> Stories</a></h6>
                        <div class="collapse" id="Stories">
                            <div class="well">

                            </div>
                        </div>
                    </li>
                    <li>
                        <h6 class="head"><a data-toggle="collapse" href="#Stories" aria-expanded="false"><i class="fa fa-comments-o"></i> Stories</a></h6>
                        <div class="collapse" id="Stories">
                            <div class="well">

                            </div>
                        </div>
                    </li>
                    <li>
                        <h6 class="head"><a data-toggle="collapse" href="#Stories" aria-expanded="false"><i class="fa fa-comments-o"></i> Stories</a></h6>
                        <div class="collapse" id="Stories">
                            <div class="well">

                            </div>
                        </div>
                    </li>
                    <li>
                        <h6 class="head"><a data-toggle="collapse" href="#Stories" aria-expanded="false"><i class="fa fa-comments-o"></i> Stories</a></h6>
                        <div class="collapse" id="Stories">
                            <div class="well">

                            </div>
                        </div>
                    </li>

                </ul>
            </div>
        </div>
    </div>

    <div class="products col-md-9">

        <div class="col-sm-4">
            <article>
                <div class="item-img">

                    <img src="~/images/product/cornerSofa/1.jpg" />
                </div>
                <a href="#." class="tittle">Köşe Takımı 1</a>

            </article>
        </div>
        <div class="col-sm-4">
            <article>
                <div class="item-img">

                    <img src="~/images/product/cornerSofa/2.jpg" />
                </div>
                <a href="#." class="tittle">Köşe Takımı 1</a>

            </article>
        </div>
        <div class="col-sm-4">
            <article>
                <div class="item-img">

                    <img src="~/images/product/cornerSofa/3.jpg" />
                </div>
                <a href="#." class="tittle">Köşe Takımı 1</a>

            </article>
        </div>
        <div class="col-sm-4">
            <article>
                <div class="item-img">

                    <img src="~/images/product/cornerSofa/4.jpg" />
                </div>
                <a href="#." class="tittle">Köşe Takımı 1</a>

            </article>
        </div>
        <div class="col-sm-4">
            <article>
                <div class="item-img">

                    <img src="~/images/product/cornerSofa/5.jpg" />
                </div>
                <a href="#." class="tittle">Köşe Takımı 1</a>

            </article>
        </div>
        <div class="col-sm-4">
            <article>
                <div class="item-img">

                    <img src="~/images/product/cornerSofa/6.jpg" />
                </div>
                <a href="#." class="tittle">Köşe Takımı 1</a>

            </article>
        </div>
        <div class="col-sm-4"> 
            <article>
                <div class="item-img">

                    <img src="~/images/product/cornerSofa/7.jpg" />
                </div>
                <a href="#." class="tittle">Köşe Takımı 1</a>

            </article>
        </div>



    </div>

</div>

PmClup/Views/Products/CornerSofa.cshtml
@{
    ViewBag.Title = "CornerSofa";
}

<h2>CornerSofa</h2>

PmClup/Views/Products/Puffs.cshtml
@{
    ViewBag.Title = "Puffs";
}

<h2>Puffs</h2>

PmClup/Views/Products/SofaSuit.cshtml
@{
    ViewBag.Title = "SofaSuit";
}

<h2>SofaSuit</h2>

PmClup/Views/Shared/_Layout.cshtml
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="M_Adnan">
    <title>@ViewBag.Title - PM CLUB</title>

    <!-- Favicon -->
    <link rel="icon" type="image/png" sizes="16x16" href="~/images/favicon.ico">

    <!-- Bootstrap Core CSS -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="~/css/ionicons.min.css" rel="stylesheet">
    <link href="~/css/main.css" rel="stylesheet">
    <link href="~/css/style.css" rel="stylesheet">
    <link href="~/css/responsive.css" rel="stylesheet">

    <!-- Online Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,600,800,200,500' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600italic,400italic,300,300italic,600,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Libre+Baskerville:400italic,400,700' rel='stylesheet' type='text/css'>

    <!-- COLORS -->
    <link rel="stylesheet" id="color" href="~/css/colors/default.css">

    <!-- JavaScripts -->
    <script src="~/js/modernizr.js"></script>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <!-- Wrap -->
    <div id="wrap">
        <!-- header -->
        <header>
            <!-- Top bar -->
            <div class="top-bar">
                <div class="top-info">
                    <div class="container">
                        <ul class="personal-info">
                            <li>
                                <p><i class="fa fa-phone"></i> +90 224 714 1414 </p>
                            </li>
                            <li>
                                <p>Müşteri Hizmetleri</p>
                            </li>
                            <li>
                                <p>info@pmclub.com.tr</p>
                            </li>
                        </ul>

                        <!-- Right Sec -->
                        <div class="right-sec">

                            <!-- Language -->
                            <select class="selectpicker">
                                <option>English</option>
                                <option>Türkçe</option>
                                <option>Arapça</option>
                            </select>

                            <!-- social -->
                            <ul class="social">
                                <li><a href="http://www.facebook.com.tr"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#."><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#."><i class="fa fa-google"></i></a></li>
                                <li><a href="#."><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Navigation -->
            <nav class="navbar">
                <div class="sticky">
                    <div class="container">
                        <!-- LOGO -->
                        <div class="logo"> <a href="@Url.Action("Index","Home")"><img class="img-responsive" src="~/images/logo.png" style="    margin-top: -15px;width: 50%;" alt=""></a> </div>
                        <!-- Nav -->
                        <ul class="nav ownmenu">
                            <li class="active"> <a href="@Url.Action("Index","Home")">Anasayfa </a> </li>
                            <li> <a href="@Url.Action("Corporate", "Home")">Kurumsal </a> </li>
                            <li>
                                <a href="#">Fuarlar </a>
                                <ul class="dropdown">
                                    <li> <a href="@Url.Action("Modef","Fairs")">Modef</a> </li>
                                    <li> <a href="@Url.Action("Imob","Fairs")">İmob</a> </li>
                                    <li> <a href="@Url.Action("ModefExpo","Fairs")">Modef Expo</a> </li>
                                    <li> <a href="@Url.Action("Modef2015","Fairs")">Modef 2015</a> </li>
                                </ul>
                            </li>
                            <li>
                                <a href="#">Ürünler </a>
                                <ul class="dropdown">
                                    <li> <a href="@Url.Action("CornerSofa","Products")">Köşe Takımları</a> </li>
                                    <li> <a href="@Url.Action("Puffs","Products")">Puflar</a> </li>
                                    <li> <a href="@Url.Action("ArmchairFor","Products")">Berjerler</a> </li>
                                    <li> <a href="@Url.Action("SofaSuit","Products")">Koltuk Takımları</a> </li>
                                </ul>
                            </li>
                             
                             <li> <a href="@Url.Action("Index","Contact")">İletişim</a> </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        @RenderBody()


   

        <!-- FOOTER -->
        <footer>
            <div class="container">
                <div class="row">
                    <p>&copy; @DateTime.Now.Year - PM-CLUP</p>

                    <!-- ABOUT -->
                    <div class="col-md-3">
                        <img src="images/logo-footer.png" alt="">
                        <div class="about-foot">
                            <ul>
                                <li>
                                    <p><i class="fa fa-map-marker"></i> 795 Folsom Ave, Suite 600, San Francisco, CA 94107</p>
                                </li>
                                <li>
                                    <p><i class="fa fa-phone"></i> +90 224 714 1414</p>
                                </li>
                                <li>
                                    <p><i class="fa fa-envelope"></i>info@pmclub.com.tr</p>
                                </li>
                            </ul>
                        </div>
                    </div>

                    <!-- Twitter Feed -->
                    <div class="col-md-3">
                        <h6>Twitter Feed</h6>
                        <ul class="tweet">
                            <li>
                                <p>A Guide to Better Brainstorming <a href="#." class="primary-color">http://enva.to/nfNrz</a> by jeff_haden </p>
                                <span>May 22, 2014</span>
                            </li>
                            <li>
                                <p>Are you a student? You only have 48 hours left to grab a full year on Tuts+ for just $45! Don't miss out. <a href="#." class="primary-color">http://ow.ly/McvuJ</a> </p>
                                <span>May 22, 2014</span>
                            </li>
                        </ul>
                    </div>

                    <!-- Photostream -->
                    <div class="col-md-3">
                        <h6>Photostream</h6>
                        <ul class="photo-steam">
                            <li><a href="#."><img src="images/photo-img-1.jpg" alt=""></a></li>
                            <li><a href="#."><img src="images/photo-img-2.jpg" alt=""></a></li>
                            <li><a href="#."><img src="images/photo-img-3.jpg" alt=""></a></li>
                            <li><a href="#."><img src="images/photo-img-4.jpg" alt=""></a></li>
                            <li><a href="#."><img src="images/photo-img-5.jpg" alt=""></a></li>
                            <li><a href="#."><img src="images/photo-img-6.jpg" alt=""></a></li>
                        </ul>
                    </div>

                    <!-- Categories -->
                    <div class="col-md-3">
                        <h6>Categories</h6>
                        <ul class="tags">
                            <li><a href="#.">User Experience</a></li>
                            <li><a href="#.">html 5</a></li>
                            <li><a href="#.">Css 3</a></li>
                            <li><a href="#.">Web Design</a></li>
                            <li><a href="#.">Social Media</a></li>
                            <li><a href="#.">Web Development</a></li>
                            <li><a href="#.">Print Design</a></li>
                            <li><a href="#.">e-commerce</a></li>
                            <li><a href="#.">Java script</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- RIGHTS -->
        <div class="rights">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <p> © All Rights Reserved <span class="primary-color">Anonim Yazilim </span></p>
                    </div>
                 </div>
            </div>
        </div>
    </div>

    <script src="~/js/jquery-1.11.0.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/own-menu.js"></script>
    <script src="~/js/jquery.isotope.min.js"></script>
    <script src="~/js/jquery.flexslider-min.js"></script>
    <script src="~/js/jquery.countTo.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.cubeportfolio.min.js"></script>
    <script src="~/js/jquery.colio.min.js"></script>
    <script src="~/js/main.js"></script>
</body>
</html>